name: "電子請求受付システムのお知らせ一覧チェック"

on:
  schedule:
    - cron: '0 10 * * *'

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: "bot"
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
  SLACK_ICON_EMOJI: ":yawning_face:"

jobs:
  diff-check:
    runs-on: ubuntu-latest
    name: "お知らせ一覧の差分取得"
    continue-on-error: true
    outputs:
      result: ${{ steps.exec.outputs.result }}
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - uses: aochmann/actions-download-artifact@1.0.4
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: result-json
          latest: true

      - name: Install puppeteer
        run: |
          PUPPETEER_PRODUCT=chrome
          deno run -A --unstable https://deno.land/x/puppeteer@9.0.2/install.ts

      - name: Run script
        id: exec
        run: |
          RESULT=$(                                 \
            deno run -A --unstable notification-diff.ts \
          )
          echo "::set-output name=result::${RESULT}"

      - uses: actions/upload-artifact@v2
        with:
          name: result-json
          path: old.json
          retention-days: 8

  notification:
    runs-on: ubuntu-latest
    name: "Slack通知"
    needs: diff-check
    steps:
      - id: check
        run: |
          if [ "${{ needs.diff-check.outputs.result }}" = "[]" ]; then
            exit 1
          fi

      - name: slack
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "お知らせ一覧の差分を検知したよ"
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "${{ needs.diff-check.outputs.result }}"
